# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='loans',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='reservation',
        ),
    ]
