# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='items',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='item',
            name='loans',
        ),
        migrations.AlterModelOptions(
            name='reader',
            options={},
        ),
        migrations.AddField(
            model_name='reader',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Reservation'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='loans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Loan'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
