# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_libraryuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryUser',
        ),
    ]
