# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('surname', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('isbn', models.IntegerField()),
                ('edition', models.IntegerField()),
                ('edition_date', models.DateField()),
                ('pages', models.IntegerField()),
                ('available', models.IntegerField()),
                ('description', models.TextField()),
                ('authors', models.ManyToManyField(blank=True, to='books.Author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField()),
                ('return_date', models.DateField()),
                ('loan_status', models.IntegerField()),
            ],
            options={
                'db_table': 'loan',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('reservation_status', models.DateField()),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='loans',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.Loan'),
        ),
        migrations.AddField(
            model_name='book',
            name='items',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.Item'),
        ),
        migrations.AddField(
            model_name='book',
            name='reservation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.Reservation'),
        ),
    ]
