# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160905_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 9, 5, 22, 5, 43, 983028)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 9, 12, 22, 5, 43, 983056)),
        ),
    ]
