# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160906_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 9, 6, 19, 55, 23, 549736)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 9, 13, 19, 55, 23, 549787)),
        ),
    ]
