# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160822_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
