# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20160822_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
        migrations.AlterField(
            model_name='item',
            name='loans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Loan'),
        ),
    ]
