# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 18:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20160906_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 8, 18, 0, 39, 441264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 8, 18, 0, 39, 441290, tzinfo=utc)),
        ),
    ]
