# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20160905_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 9, 6, 19, 15, 26, 41335)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 9, 13, 19, 15, 26, 41387)),
        ),
    ]
