# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 18:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160908_1820'),
        ('books', '0005_auto_20160908_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='readers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Reader'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='readers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Reader'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 8, 18, 20, 17, 280101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 18, 20, 17, 280125, tzinfo=utc)),
        ),
    ]
