# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20160827_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
